version: '2.2'

services:
  tomcat:
    image: futmanager
    build: .
    ports:
      - '8888:8080'
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    volumes: 
      - ./target/futmanager.war:/usr/local/tomcat/webapps/futmanager.war
    networks:
      - dbconection
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=futmanager
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3307:3306'
    networks:
      - dbconection
  
volumes:
  mysql-data:
    driver: local
networks:
  dbconection:
    driver: bridge