version: '2.2'
services:
    app-web:  
        build: .
        ports:
            - "8081:8080"
        links:
            - app-db

    app-db:  
        build: ./db
        ports:
            - "5432:5432"
        volumes_from:
            - app-db-data

    app-db-data:  
        image: cogniteev/echo
        command: echo 'Data Container for PostgreSQL'
        volumes:
            - /var/lib/postgresql/data