version: '2'
services:
  app-web:  
    build: .
    ports:
      - "8888:8080"
    depends_on:
      - app-db
    networks :
      - mt-network

  app-db:  
    build: ./db
    ports:
      - "5433:5432"
    networks:
      - mt-network
  
    
volumes:
  psql-data:
    driver: local

networks:
  mt-network:
    driver: bridge